name: Deploy on issues update

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - labeled
      - unlabeled

# The workflow has conditional execution, when
# 1. the updated issue (blog post) has the label meta:published, or
# 2. an issue had the meta:published label removed

jobs:
  deploy:
    if: >-
      (contains(github.event.issue.labels.*.name, 'meta:published')) ||
      (github.event.action == 'unlabeled' && github.event.label.name == 'meta.published')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest
      # - name: Pull Vercel Environment Information
      #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Build Project Artifacts
      #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
